### ISSUE TITLE
Test examples bug

### ISSUE THREAD

**Issue by Liuzichi** [firdauslubis88/NISwGSP#4]
I successfully compiled the *.exe file on Windows.When I run the examples you provided，Some of them work properly to get results. But most of examples get bug as following:
![image](https://user-images.githubusercontent.com/39233223/57756003-e4a41f80-7724-11e9-8189-9a61a898fa31.png)
I'm a new programmer,can't find out where bug is!! Please help me to solve this problem or teach me how to debug! Please!!!

**Comment by hub-wll** [comment]
Hello, I have the same problem with you today, do you have solve this problem? 

![11](https://user-images.githubusercontent.com/52961658/77384678-f3d21000-6dc0-11ea-9627-bccf87074bde.png)

**Comment by Liuzichi** [comment]
https://github.com/firdauslubis88/NISwGSP/issues/4#issuecomment-602988647
If i remember correctly，there is a file that needs to add some code.
Add the code " sort(result.begin(), result.end()); "
before the return statement of the function GetImageFileNamesInDir  of the file Parameter.cpp
![image](https://user-images.githubusercontent.com/39233223/77385548-67751c80-6dc3-11ea-9e8e-3987fdd9ad39.png)
I have used it successfully under ubuntu system, but I have n’t used it for a long time. I may remember it wrongly. If the above code is not successful, you can send me an email. 
My email is liuzichi@foxmail.com

**Comment by Liuzichi** [comment]
> Hello, I have the same problem with you today, do you have solve this problem?
> 
> ![11](https://user-images.githubusercontent.com/52961658/77384678-f3d21000-6dc0-11ea-9627-bccf87074bde.png)

**Comment by jchhuang** [comment]
I operate as Liuzichi suggestion, however, this issue is still existing. Does any other solution for it?
